### ISSUE TITLE
Freezing the module prevents code updates

### ISSUE THREAD

**Issue by rickmcgeer** [jupyterlab/extension-cookiecutter-ts#248] opened 2022-11-26 04:32 UTC
## Description

Once an extension is packaged as recommended in https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html#extension-tutorial, updates to the code are no longer reflected in the extension, even after `jlpm clean:all` is run.  The pattern is to make a code change, then test it.  The JavaScript code viewed in the browser debugger is the code before the change.  However, the compiled JavaScript code in both the lib and extension/lib directories reflect the change.
There is obviously some caching behavior going on here, and it only happens when the extension is packaged with pyproject.toml.  However, I can't find and remove the cached extension and force  a rebuild.  The best I've been able to do is to blow away the entire directory, clone the git repo containing the extension, and rebuild from scratch.  This is obviously a highly-inefficient procedure.

## Reproduce

1. Build an extension
2. Package it, using pyproject,toml
3. Change it in some way, recompile using jlpm run build
4. Open JupyterLab, open the source code for the extension in the browser debugger, and see the old source code
5. Check and see the new compiled source in lib

## Expected behavior

Obviously, I'd like changes in the source code in the build.

## Context
Source code in the Chrome debugger:
```
const urls = {
            deploy: {
                en: 'https://matt.engageLively.com/users/rick/published/studio/index.html?',
                ja_JP: 'https://matt.engageLively.com/users/rick/published/studio/index.html?'
            },
            beta: {
                en: 'https://matt.engageLively.com/users/rick/published/studio/index.html?',
                ja_JP: 'https://matt.engageLively.com/users/rick/published/studio/index.html?'
            },
}
```
Source code in extension.lib:
```
const urls = {
            deploy: {
                en: 'https://matt.engageLively.com/users/rick/published/studio-old/index.html?',
                ja_JP: 'https://matt.engageLively.com/users/rick/published/studio-old/index.html?'
            },
            beta: {
                en: 'https://matt.engageLively.com/users/rick/published/studio/-oldindex.html?',
                ja_JP: 'https://matt.engageLively.com/users/rick/published/studio-old/index.html?'
            }

}
```

Source code in src (ts code):
```
const urls = {
            deploy: {
                en: 'https://matt.engageLively.com/users/rick/published/studio-old/index.html?',
                ja_JP: 'https://matt.engageLively.com/users/rick/published/studio-old/index.html?'
            },
            beta: {
                en: 'https://matt.engageLively.com/users/rick/published/studio/-oldindex.html?',
                ja_JP: 'https://matt.engageLively.com/users/rick/published/studio-old/index.html?'
            }

}
```

Here's package.json:
```
{
  "name": "jupyterlab-universal-extension",
  "version": "0.1.0",
  "description": "A general plugin which permits a third-party editor to be integrated into JupyterLab, in a JupyterLab tab or tabs, and reading and writing the user's filesystem through JupyterLab",
  "keywords": [
    "jupyter",
    "jupyterlab",
    "jupyterlab-extension"
  ],
  "homepage": "https:://engageLively.com/jupyterlab-universal-extension",
  "bugs": {
    "url": "https:://engageLively.com/jupyterlab-universal-extension/issues"
  },
  "license": "BSD-3-Clause",
  "author": {
    "name": "Rick McGeer",
    "email": "rick@mcgeer.com"
  },
  "files": [
    "lib/**/*.{d.ts,eot,gif,html,jpg,js,js.map,json,png,svg,woff2,ttf}",
    "style/**/*.{css,js,eot,gif,html,jpg,json,png,svg,woff2,ttf}",
    "schema/*.json"
  ],
  "main": "lib/index.js",
  "types": "lib/index.d.ts",
  "style": "style/index.css",
  "repository": {
    "type": "git",
    "url": "https:://engageLively.com/jupyterlab-universal-extension.git"
  },
  "scripts": {
    "build": "jlpm build:lib && jlpm build:labextension:dev",
    "build:prod": "jlpm clean && jlpm build:lib && jlpm build:labextension",
    "build:labextension": "jupyter labextension build .",
    "build:labextension:dev": "jupyter labextension build --development True .",
    "build:lib": "tsc",
    "clean": "jlpm clean:lib",
    "clean:lib": "rimraf lib tsconfig.tsbuildinfo",
    "clean:lintcache": "rimraf .eslintcache .stylelintcache",
    "clean:labextension": "rimraf jupyterlab_universal_extension/labextension",
    "clean:all": "jlpm clean:lib && jlpm clean:labextension && jlpm clean:lintcache",
    "eslint": "jlpm eslint:check --fix",
    "eslint:check": "eslint . --cache --ext .ts,.tsx",
    "install:extension": "jlpm build",
    "lint": "jlpm stylelint && jlpm prettier && jlpm eslint",
    "lint:check": "jlpm stylelint:check && jlpm prettier:check && jlpm eslint:check",
    "prettier": "jlpm prettier:base --write --list-different",
    "prettier:base": "prettier \"**/*{.ts,.tsx,.js,.jsx,.css,.json,.md}\"",
    "prettier:check": "jlpm prettier:base --check",
    "stylelint": "jlpm stylelint:check --fix",
    "stylelint:check": "stylelint --cache \"style/**/*.css\"",
    "test": "jest --coverage",
    "version": "tsc --version",
    "watch": "run-p watch:src watch:labextension",
    "watch:src": "tsc -w",
    "watch:labextension": "jupyter labextension watch ."
  },
  "dependencies": {
    "@jupyterlab/application": "^3.1.0",
    "@jupyterlab/apputils": "^3.5.0",
    "@jupyterlab/codeeditor": "^3.5.0",
    "@jupyterlab/docmanager": "^3.5.0",
    "@jupyterlab/docregistry": "^3.5.0",
    "@jupyterlab/filebrowser": "^3.5.0",
    "@jupyterlab/fileeditor": "^3.5.0",
    "@jupyterlab/launcher": "^3.5.0",
    "@jupyterlab/mainmenu": "^3.5.0",
    "@jupyterlab/markdownviewer": "^3.5.0",
    "@jupyterlab/notebook": "^3.5.0",
    "@jupyterlab/observables": "^4.5.0",
    "@jupyterlab/rendermime": "^3.5.0",
    "@jupyterlab/services": "^6.5.0",
    "@jupyterlab/settingregistry": "^3.5.0",
    "@jupyterlab/shared-models": "^3.5.0",
    "@jupyterlab/ui-components": "^3.5.0",
    "@lumino/coreutils": "^1.12.1",
    "@lumino/signaling": "^1.11.0",
    "@lumino/widgets": "^1.35.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@jupyterlab/builder": "^3.1.0",
    "@jupyterlab/testutils": "^3.0.0",
    "@types/jest": "^26.0.0",
    "@typescript-eslint/eslint-plugin": "^4.8.1",
    "@typescript-eslint/parser": "^4.8.1",
    "eslint": "^7.14.0",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-prettier": "^3.1.4",
    "jest": "^26.0.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.1.1",
    "rimraf": "^3.0.2",
    "stylelint": "^14.3.0",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-config-recommended": "^6.0.0",
    "stylelint-config-standard": "~24.0.0",
    "stylelint-prettier": "^2.0.0",
    "ts-jest": "^26.0.0",
    "typescript": "~4.1.3"
  },
  "sideEffects": [
    "style/*.css",
    "style/index.js"
  ],
  "styleModule": "style/index.js",
  "publishConfig": {
    "access": "public"
  },
  "jupyterlab": {
    "extension": true,
    "outputDir": "jupyterlab_universal_extension/labextension",
    "schemaDir": "schema"
  },
  "jupyter-releaser": {
    "hooks": {
      "before-build-npm": [
        "python -m pip install jupyterlab~=3.1",
        "jlpm"
      ],
      "before-build-python": [
        "jlpm clean:all"
      ]
    }
  }
}
```

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by fcollonval** [comment] 2022-11-28 09:52
@rickmcgeer 

I cannot reproduce this. I ran:

1. `python -m cookiecutter https://github.com/jupyterlab/extension-cookiecutter-ts` - using default inputs
2. `python -m pip install -e ".[test,dev]"`
3. `jupyter labextension develop --overwrite .`
4. Check the default log message
5. Changed the console log message and check it was applied
6. `python -m build .`
7. Changed the console log message again and check it was applied

Did you installed the packaged extension? If so this is the reason of the bug. Installing the packaged extension will remove the symlink to your development environment.

If you think web browser cache may be at play, you can use `Ctrl+F5` to invalidate the cache (or use the web browser option to do so).

**Comment by rickmcgeer** [comment] 2022-11-28 14:53
@fcollonval

thanks very much for the prompt response and for trying to reproduce this, and sorry if there was any issue.

I checked the web browser cache, and did a hard refresh (right click on load with dev tools open).  I also removed node_modules and lib, and lib in the packaged extension directory, and I found the same issue.

I did install the packaged extension, and I think you're right, that's the problem.  The real question (and then we can close this out) is how do I uninstall it, or is what I am doing now (re-cloning the repo) the right answer?  Whatever the answer is, I do think it should be documented, because others may make the same mistake/run into the same issue I did.  This is particularly the case because I've been constantly updating the extension to keep up with changes in jupyterlab (the changes I made here were because, when I recompiled with an updated version of jupyterlab, I was getting no-such-method exceptions, so I added stubs for the missing functions and recompiled).  It's entirely possible that other extension developers have to update their extensions relatively frequently to keep up with changes in the underlying code base.

Thanks again for your help.

The extension, BTW, is in this github repo: [https://github.com/engageLively/jupyterlab-universal-extension](https://github.com/engageLively/jupyterlab-universal-extension).  (So named because we hoped that it could be retargeted at any Web-based editor, changing only a few lines of JSON.  The changes that I made that weren't showing up in the browser debugger were due to minor additions to the `GalyleoEditor` class to make it compatible with updates to the (effective) Widget API.

**Comment by fcollonval** [comment] 2022-11-28 15:11
If you installed the packaged extension, you can restored the development version by running:

```sh
# Uninstall the frozen assets
python -m pip uninstall <python-package-name>
# Install the extension in development mode
cd <extension-development-folder>
python -m pip install -e ".[test,dev]"
jupyter labextension develop --overwrite .
```

You don't need to clone again your code or to nuke your environment.

**Comment by rickmcgeer** [comment] 2022-11-29 04:48
@fcollonval 
Merci beaucoup!  I suggest we put this in the tutorial docs...
I am going to rewrite the extension anyway, to take advantage of the Yjs technology.  It largely replicates the functionality in [https://github.com/jupyterlab/extension-examples/tree/master/documents](https://github.com/jupyterlab/extension-examples/tree/master/documents) (you may know something about that :-)) except that the editor is an external editor that sits in an iframe in a JupyterLab tab: the read/write etc calls just pass messages to the external editor in the iframe.

**Comment by fcollonval** [comment] 2023-03-20 10:51
Closing as answered

**Closed as completed by fcollonval** 2023-03-20 10:51 UTC
Labels: question
